### ISSUE TITLE
Issue rendering PDF when selecting a file

### ISSUE THREAD

**Issue by shivaycb** [couchbase-examples/vector-search-nodejs#6]
![image](https://github.com/user-attachments/assets/c2813af5-1b7b-4bd7-80c8-9dac1ecbac8f)

In this example we are trying to upload a PDF, once the user uploads the pdf, the PDF file gets stored in the assets directory. And then we use the React PDF Viewer to show the PDF that has been stored in the assets folder. 

Currently we are unable to load PDF and show it inside the PDF viewer component.  This is a likely issue with the Vercel AI SDK with Nextjs, where data is not getting transferred from the server side <> client side.

**Comment by lokeshgoel177** [comment]
Resolved
